/**
 * scripts/parser_baseline.mjs  — M1A: parser baseline (no telemetry).
 *
 * Answers "what does Elocin understand today?" purely from the preserved
 * evidence model (observations + interpretations). Ugly terminal output on
 * purpose — no UI. Run: node --env-file=.env scripts/parser_baseline.mjs
 *
 * Scopes to REAL orgs (excludes 'test-org-%' detritus left by the test suite).
 * Precision/correction need teacher corrections; when there are ~none it says
 * so instead of printing a meaningless 100%.
 */
import { query } from '../src/data/db.js'

const REAL_ORG = `o2.slug NOT LIKE 'test-org-%'`
const pct = (n, d) => (d ? Math.round((100 * n) / d) : 0)
const bar = (label, n, d) => `  ${label.padEnd(12)} ${String(n).padStart(3)}  (${pct(n, d)}%)`

// --- pull the current interpretation payload for every real, live note -------
const { rows } = await query(`
  SELECT o.id, COALESCE(o.current_text, o.raw_text) AS text, i.payload
  FROM observations o
  JOIN teams t  ON t.id = o.team_id
  JOIN organizations o2 ON o2.id = t.organization_id
  JOIN interpretations i ON i.observation_id = o.id AND i.is_current
  WHERE o.is_deleted = FALSE AND ${REAL_ORG}
`)

const N = rows.length
const conf = {}, out = {}, skillAuto = {}, skillSuggest = {}
let unknownWithContent = 0
const lowNotes = [], unknownRichNotes = []

for (const r of rows) {
  const p = r.payload || {}
  conf[p.confidence || 'null'] = (conf[p.confidence || 'null'] || 0) + 1
  out[p.outcome || 'unknown'] = (out[p.outcome || 'unknown'] || 0) + 1
  for (const s of p.skills || []) skillAuto[s] = (skillAuto[s] || 0) + 1
  for (const s of (p.suggestions?.skills || [])) skillSuggest[s] = (skillSuggest[s] || 0) + 1
  if (p.confidence === 'LOW') lowNotes.push(r.text)
  // a note that names skills/actions but the engine found NO outcome = outcome recall gap
  if ((p.outcome || 'unknown') === 'unknown' && ((p.skills || []).length || (p.suggestions?.skills || []).length)) {
    unknownWithContent++
    unknownRichNotes.push(r.text)
  }
}

// --- precision / correction from rules-vs-teacher pairs -----------------------
const { rows: pairs } = await query(`
  SELECT r.payload->'skills' AS rules_skills, t.payload->'skills' AS teacher_skills
  FROM interpretations r
  JOIN interpretations t ON t.observation_id = r.observation_id AND t.source='teacher' AND t.is_current
  JOIN organizations o2 ON o2.id = r.organization_id
  WHERE r.source='rules' AND ${REAL_ORG.replace('o2.slug', 'o2.slug')}
`)
let kept = 0, removed = 0, added = 0
for (const pr of pairs) {
  const rs = new Set(pr.rules_skills || []), ts = new Set(pr.teacher_skills || [])
  for (const s of rs) (ts.has(s) ? kept++ : removed++)
  for (const s of ts) if (!rs.has(s)) added++
}
const corrections = pairs.length

const top = (obj, k = 6) => Object.entries(obj).sort((a, b) => b[1] - a[1]).slice(0, k)

console.log(`
Elocin Parser Baseline (M1A)
============================
Corpus: ${N} real, live observations (test-org data excluded)

Confidence`)
for (const [k, v] of [['HIGH', conf.HIGH || 0], ['MEDIUM', conf.MEDIUM || 0], ['LOW', conf.LOW || 0]]) console.log(bar(k, v, N))

console.log(`\nOutcome`)
for (const k of ['positive', 'negative', 'mixed', 'unknown']) console.log(bar(k, out[k] || 0, N))
console.log(`  -> outcome UNKNOWN despite skills/actions present: ${unknownWithContent}/${N} (${pct(unknownWithContent, N)}%)  <-- outcome recall gap`)

console.log(`\nTrust (needs teacher corrections)`)
if (corrections < 5) {
  console.log(`  INSUFFICIENT DATA: only ${corrections} corrected note(s) exist.`)
  console.log(`  Precision/correction-rate are NOT meaningful until real teachers correct.`)
  console.log(`  (Seed notes were generated by the parser itself, so rules==teacher by construction.)`)
} else {
  console.log(`  Precision (upper bound): ${pct(kept, kept + removed)}%   (kept ${kept} / removed ${removed})`)
  console.log(`  Recall estimate:         ${pct(kept, kept + added)}%   (missed ${added})`)
  console.log(`  Correction rate:         ${pct(corrections, N)}%   (${corrections}/${N} notes corrected)`)
}

console.log(`\nTop auto-tagged skills`)
for (const [s, c] of top(skillAuto)) console.log(`  ${String(c).padStart(3)}  ${s}`)

console.log(`\nTop RECALL CANDIDATES (seen as suggestions, never auto-applied)`)
for (const [s, c] of top(skillSuggest)) console.log(`  ${String(c).padStart(3)}  ${s}`)

console.log(`\nLOW-confidence notes (engine connected ~nothing):`)
for (const t of lowNotes.slice(0, 6)) console.log(`  - ${JSON.stringify(t)}`)

console.log(`\nSample: success described but scored outcome=unknown (recall gap):`)
for (const t of unknownRichNotes.slice(0, 6)) console.log(`  - ${JSON.stringify(t)}`)

console.log('')
process.exit(0)
