/**
 * lexicon.test.js — Lexicon v1 + method-taxonomy coverage.
 * Pure engine/normalizer tests, no DB required.
 */
import { test, describe } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { parseObservation } from '../engine/index.js'
import { normalizeExact, expandAbbreviations, stemToken } from '../core/rules/normalize.js'

const methodKeys = (p) => p.methods.map((m) => m.key)
const suggMethodKeys = (p) => p.suggestions.methods.map((m) => m.key)
const HERE = dirname(fileURLToPath(import.meta.url))

// ---------------------------------------------------------------------------
// Correction 1 (highest priority) — seed-note regression lock.
// Every note in the demo seed must keep parsing exactly as committed. The
// fixture is regenerated by scripts/gen_seed.mjs alongside the seed; if an
// engine change alters any seed parse, this fails and must be done knowingly.
// ---------------------------------------------------------------------------
describe('Seed-parse regression lock', () => {
  const fixture = JSON.parse(readFileSync(join(HERE, 'fixtures', 'seed_parses.json'), 'utf8'))
  test(`fixture present with ${fixture.notes.length} notes`, () => {
    assert.ok(fixture.notes.length >= 30)
  })
  for (const { raw, parsed } of fixture.notes) {
    test(`stable parse: "${raw.slice(0, 48)}"`, () => {
      // seed org enables no packs
      assert.deepEqual(parseObservation(raw, { context: parsed.context, roster: parsed.students }), parsed)
    })
  }
})

// ---------------------------------------------------------------------------
// Correction 5 — precedence / negation / no double-counting.
// ---------------------------------------------------------------------------
describe('Precedence rules', () => {
  test('"without" AFTER the trigger does not negate; note is mixed (Emma seed note)', () => {
    const p = parseObservation('Emma struggled with CVC blending but got 3/5 with picture cards vs 1/5 without.', { roster: ['Emma'] })
    const visual = p.methods.find((m) => m.key === 'visual')
    assert.ok(visual, 'visual should be detected')
    assert.equal(visual.negated, false, '"without" trails the trigger → not negated')
    assert.equal(p.outcome, 'mixed')
  })
  test('"without" directly before a trigger negates it', () => {
    const p = parseObservation('Ava read the passage without picture cards today', { roster: ['Ava'] })
    assert.equal(p.methods.find((m) => m.key === 'visual').negated, true)
  })
  test('negation only fires within 4 words before the trigger', () => {
    const near = parseObservation('Ava did not use the picture cards', { roster: ['Ava'] })
    assert.equal(near.methods.find((m) => m.key === 'visual').negated, true)
    const far = parseObservation('Ava was not here yesterday but today used the picture cards well', { roster: ['Ava'] })
    assert.equal(far.methods.find((m) => m.key === 'visual').negated, false)
  })
  test('a negation token is not double-counted as a negative outcome', () => {
    // "not" negates the method; the only outcome word is "independently" (positive)
    const p = parseObservation('Ava did not use picture cards but worked independently', { roster: ['Ava'] })
    assert.equal(p.methods.find((m) => m.key === 'visual').negated, true)
    assert.equal(p.outcome, 'positive')
  })
  test('"independently" plays a dual role: independent method AND positive outcome', () => {
    const p = parseObservation('Ava worked independently on her counting', { roster: ['Ava'] })
    assert.ok(methodKeys(p).includes('independent'))
    assert.equal(p.outcome, 'positive')
  })
})

// ---------------------------------------------------------------------------
// Correction 3 — per-trigger tiers.
// ---------------------------------------------------------------------------
describe('Trigger tiers', () => {
  test('single common noun (cube) is MEDIUM → suggestion, not auto', () => {
    const p = parseObservation('Ava counted with a cube', { roster: ['Ava'] })
    assert.ok(!methodKeys(p).includes('kinesthetic'))
    assert.ok(suggMethodKeys(p).includes('kinesthetic'))
  })
  test('unambiguous term (unifix) is HIGH → auto-applied', () => {
    const p = parseObservation('Ava built the number with unifix cubes', { roster: ['Ava'] })
    assert.ok(methodKeys(p).includes('kinesthetic'))
  })
  test('number line is reclassified from counting skill to the visual method', () => {
    const p = parseObservation('Ava used the number line to add', { roster: ['Ava'] })
    assert.ok(methodKeys(p).includes('visual'))
    assert.ok(!p.skills.includes('counting'))
  })
  test('one to one is its own skill (not a counting trigger)', () => {
    const p = parseObservation('Ava used one to one correspondence to count the bears', { roster: ['Ava'] })
    assert.ok(p.skills.includes('one_to_one'))
  })
})

// ---------------------------------------------------------------------------
// Correction 6 — pattern signals.
// ---------------------------------------------------------------------------
describe('Structural patterns', () => {
  test('attempts pattern → repetition method', () => {
    assert.ok(methodKeys(parseObservation('Ava blended it on the 3rd try', { roster: ['Ava'] })).includes('repetition'))
  })
  test('prompt-count pattern → verbal_prompt method', () => {
    assert.ok(methodKeys(parseObservation('Ava lined up after 2 prompts', { roster: ['Ava'] })).includes('verbal_prompt'))
  })
  test('score pattern contributes a positive outcome', () => {
    assert.equal(parseObservation('Ava got 4 of 5 correct', { roster: ['Ava'] }).outcome, 'positive')
  })
})

describe('Method taxonomy — every one of the 16 keys matches a realistic note', () => {
  const cases = {
    visual:          'Ava used picture cards to sort the sounds today',
    kinesthetic:     'Ava used unifix cubes and manipulatives to build the number',
    gestural:        'Ava used a hand signal and finger tracing for each sound',
    verbal_prompt:   'Ava needed a verbal prompt to begin the task',
    physical_assist: 'Ava needed hand over hand to guide the pencil',
    modeling:        'the teacher modeled the strategy before she tried it',
    one_on_one:      'Ava worked one on one at the teacher table',
    small_group:     'Ava worked in a small group during literacy',
    whole_group:     'during whole group carpet time Ava listened well',
    partner:         'Ava worked with a partner during turn and talk',
    independent:     'Ava did independent practice on her own quietly',
    repetition:      'lots of repetition helped Ava with her sound drill',
    music_chant:     'Ava sang a counting song with the class',
    sensory:         'Ava used a wiggle seat and a sensory break to focus',
    reinforcement:   'Ava earned a spot on her token board today',
    chunking:        'we broke it down step by step for Ava'
  }
  for (const [key, sentence] of Object.entries(cases)) {
    test(`method '${key}' detected`, () => {
      assert.ok(methodKeys(parseObservation(sentence, { roster: ['Ava'] })).includes(key),
        `expected '${key}', got ${JSON.stringify(methodKeys(parseObservation(sentence, { roster: ['Ava'] })))}`)
    })
  }
  test('old group/guided keys are gone; group work → small_group', () => {
    const p = parseObservation('Ava did well in group work today', { roster: ['Ava'] })
    assert.ok(methodKeys(p).includes('small_group'))
    assert.ok(!methodKeys(p).includes('group'))
  })
})

describe('Normalization + stemming', () => {
  test('lowercases, strips apostrophes, keeps : and -', () => {
    assert.equal(normalizeExact("  Can’t work 1:1 or 1-on-1  "), 'cant work 1:1 or 1-on-1')
  })
  test('stemToken strips regular inflections', () => {
    assert.equal(stemToken('blending'), 'blend')
    assert.equal(stemToken('cards'), 'card')
    assert.equal(stemToken('tries'), 'try')
    assert.equal(stemToken('running'), 'run')
  })
  test('1:1 / 1-on-1 both map to one_on_one (normalization preserves : and -)', () => {
    assert.ok(methodKeys(parseObservation('Ava worked 1:1 then 1-on-1 with me', { roster: ['Ava'] })).includes('one_on_one'))
  })
  test('a stemmed-only skill match is a suggestion, not auto', () => {
    const p = parseObservation('Ava decoded three of the words', { roster: ['Ava'] })
    assert.ok(p.suggestions.skills.includes('phonics'))
    assert.ok(!p.skills.includes('phonics'))
  })
})

describe('Abbreviations', () => {
  test('expandAbbreviations maps multi-word forms', () => {
    assert.equal(expandAbbreviations('num line in sm grp', { 'num line': 'number line', 'sm grp': 'small group' }), 'number line in small group')
  })
  test('an abbreviation-only match is a suggestion', () => {
    const p = parseObservation('Ava worked in a sm grp during maths', { roster: ['Ava'] })
    assert.ok(suggMethodKeys(p).includes('small_group'))
    assert.ok(!methodKeys(p).includes('small_group'))
  })
})

// ---------------------------------------------------------------------------
// Correction 8 — eight curriculum packs, no leak into core behaviour.
// ---------------------------------------------------------------------------
describe('Curriculum packs (opt-in, no leak)', () => {
  const cases = [
    ['montessori', 'Ava used the golden beads to count', 'kinesthetic'],
    ['reggio', 'Ava explored the loose parts at the atelier', 'kinesthetic'],
    ['waldorf', 'the class did eurythmy this morning', 'gestural'],
    ['highscope', 'we did plan-do-review before centers', 'chunking'],
    ['creative_curriculum', 'used an intentional teaching card', 'modeling'],
    ['tools_of_the_mind', 'Ava made a play plan first', 'visual'],
    ['structured_literacy', 'we used elkonin boxes to segment', 'visual'],
    ['structured_math', 'a number talk about making ten', 'whole_group']
  ]
  for (const [pack, sentence, key] of cases) {
    test(`${pack}: inert without pack, active with it`, () => {
      assert.ok(!methodKeys(parseObservation(sentence, { roster: ['Ava'] })).includes(key), `${key} leaked without pack`)
      assert.ok(methodKeys(parseObservation(sentence, { roster: ['Ava'], packs: [pack] })).includes(key), `${key} missing with pack`)
    })
  }
  test('unknown pack names are ignored', () => {
    assert.doesNotThrow(() => parseObservation('Ava read a book', { roster: ['Ava'], packs: ['nope'] }))
  })
})

describe('Additive parsed_json fields + invariants', () => {
  test('methods carry source, output stamps lexicon version, suggestions present', () => {
    const p = parseObservation('Ava used picture cards to read the passage', { roster: ['Ava'] })
    assert.equal(p.lexicon, '1.3')
    assert.ok(p.methods.every((m) => m.source === 'auto'))
    assert.ok(Array.isArray(p.suggestions.skills) && Array.isArray(p.suggestions.methods))
  })
  test('confidenceScore stays within the locked 0..4 range', () => {
    for (const n of ['Ava mastered counting to 20 with unifix cubes, 5/5 first time', 'ok', 'cant read any big words with a flash card']) {
      const s = parseObservation(n, { roster: ['Ava'] }).confidenceScore
      assert.ok(s >= 0 && s <= 4, `${s} out of range for "${n}"`)
    }
  })
})
